CREATE TABLE style(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE beer(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	sku VARCHAR(50) NOT NULL,
	name VARCHAR(80) NOT NULL,
	description TEXT NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	alcohol_strength DECIMAL(10,2) NOT NULL,
	comission DECIMAL(10,2) NOT NULL,
	flavour VARCHAR(50) NOT NULL,
	origin VARCHAR(50) NOT NULL,
	style_id BIGINT(20) NOT NULL,
	FOREIGN KEY(style_id) REFERENCES style(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

